name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: portfolioregistry014.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: portfolioregistry014.azurecr.io/portfolio-app:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.REGISTRY_USERNAME }}","clientSecret":"${{ secrets.REGISTRY_PASSWORD }}","tenantId":"066500e6-1ea3-489f-a0df-f24589173738","subscriptionId":"a03f95c9-6918-4ac5-b7ca-3b95e7ec830f"}'

    - name: Deploy container to Azure Web App
      run: |
        az webapp config container set \
          --name umar-devops-portfolio \
          --resource-group devops-portfolio-rg \
          --docker-custom-image-name portfolioregistry014.azurecr.io/portfolio-app:latest \
          --docker-registry-server-url https://portfolioregistry014.azurecr.io \
          --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
          --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}